### ISSUE TITLE
Stdlib is install in the folder lib_root/Blanqui/Lib instead of lib_root/Stdlib

### ISSUE THREAD

**Issue by NotBad4U** [Deducteam/opam-lambdapi-repository#4]
When I follow the [README](https://github.com/Deducteam/opam-lambdapi-repository/blob/master/README.md) instructions for adding `lambdapi-*` opam repo and install  the `lambdapi-stdlib` through opam,
the library files are installed _strangely_ in the directory `lib_root/Blanqui/Lib`. But if I clone in local the `lambdapi-stdlib` repository and run the command `make install` in the directory, it install the files in the expected directory `lib_root/Stdlib`.

This difference causes us to import the stdlib with this query `require open Blanqui.Lib.Nat;` instead of doing `require open Stdlib.Prop;`

Logs of my install:
```sh
❯ opam install lambdapi-stdlib
The following actions will be performed:
  - install lambdapi-stdlib 1.0.0

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> retrieved lambdapi-stdlib.1.0.0  (cached)
-> installed lambdapi-stdlib.1.0.0
Done.

lib/lambdapi/lib_root took 6s
❯ ls -l
drwxr-xr-x@ - alessiocoltellacci 19 Oct 20:25 Blanqui
```

### Note:
I am interested by this question for Carcara + CI for Lambdapi

**Comment by fblanqui** [comment]
Hi Alessio. Thank you for the issue! The src url was wrong. I fixed it.
Please opam update; opam uninstall lambdapi-stdlib; opam install lambdapi-stdlib
It should work now hopefully.

**Comment by fblanqui** [comment]
There is still a problem in the tar.gz file.

**Comment by fblanqui** [comment]
This is fixed now.
